DROP TABLE IF EXISTS users;

CREATE TABLE users
(
    id                   SERIAL PRIMARY KEY,
    name                 VARCHAR(255),
    lastname             VARCHAR(255),
    email                VARCHAR(255) UNIQUE,
    password_hash        VARCHAR(255),
    role                 VARCHAR(50),
    refresh_token        VARCHAR(255),
    reset_password_token VARCHAR(255),
    created_at           TIMESTAMP DEFAULT NOW(),
    updated_at           TIMESTAMP DEFAULT NOW()
);

INSERT INTO users (name, lastname, email, password_hash, role)
VALUES ('Test', 'Testowy', 'admin@admin.com', '$2b$10$j1yPpwKj7Qilx6ycaHf2A.U.sNOK6lcnU61KyEGmkFuDx9uugiTXK', 'admin');


DROP TABLE IF EXISTS refresh_tokens;

CREATE TABLE refresh_tokens
(
    id            SERIAL PRIMARY KEY,
    user_id       INT REFERENCES "users" (id),
    refresh_token VARCHAR
);


DROP TABLE IF EXISTS calendar;

CREATE TABLE calendar
(
    id       SERIAL PRIMARY KEY,
    user_id  INT REFERENCES "users" (id),
    title    VARCHAR NOT NULL,
    content  VARCHAR NOT NULL,
    priority INT     NOT NULL,
    date     VARCHAR NOT NULL
);

INSERT INTO calendar (user_id, title, content, priority, date)
VALUES (1, 'testowy temat', 'testowa wiadomość', 1, '12/1/2024'),
       (1, 'testowy temat2', 'testowa wiadomość2', 3, '3/2/2024');


DROP TABLE IF EXISTS navigation;

CREATE TABLE navigation
(
    id        SERIAL PRIMARY KEY,
    name_pl   VARCHAR NOT NULL,
    name_en   VARCHAR NOT NULL,
    route     VARCHAR NOT NULL,
    published BOOLEAN NOT NULL DEFAULT TRUE,
    user_only BOOLEAN NOT NULL DEFAULT FALSE
);

INSERT INTO navigation (name_pl, name_en, route)
VALUES ('Etapy ciąży', 'Stages of pregnancy', '/stages'),
       ('Zdrowie', 'Health', '/health'),
       ('Wyprawka', 'Layette', '/layette');

INSERT INTO navigation (name_pl, name_en, route, user_only)
VALUES ('Kalendarz', 'Calendar', '/calendar', TRUE);


DROP TABLE IF EXISTS pregnancy_stages;

CREATE TABLE pregnancy_stages
(
    id              SERIAL PRIMARY KEY,
    week            INT NOT NULL UNIQUE,
    description_pl  VARCHAR,
    description_en  VARCHAR,
    image_header_pl VARCHAR,
    image_header_en VARCHAR,
    length_cm       VARCHAR DEFAULT '',
    weight_kg       VARCHAR DEFAULT ''
);

INSERT INTO pregnancy_stages (week, description_pl, description_en, image_header_pl, image_header_en, length_cm,
                              weight_kg)
VALUES (1,
        'Twój organizm przygotowuje się do ewentualnego zapłodnienia. Masz miesiączkę, co oznacza, że błona macicy złuszcza się, a na jej miejsce pojawia się nowy nabłonek – to pozwoli jej przyjąć zapłodnione jajeczko. W tym czasie wzrasta poziom estrogenów, umożliwiający przebieg owulacji.',
        '',
        'Przygotowanie',
        'Preparation',
        '',
        ''),
       (2,
        'Kończy się krwawienie, a w twoich jajnikach rosną pęcherzyki Graffa. Za kilka dni jeden z nich dojrzeje na tyle, aby uwolnić komórkę jajową do jajowodu (to tzw. jajeczkowanie, czyli owulacja). W szyjce macicy pojawia się gęsty śluz w ciąży, który ułatwi plemnikowi dotarcie do komórki jajowej.',
        '',
        'Proces zapłodnienia',
        'Fertilization process',
        '',
        ''),
       (3,
        'To moment owulacji, a więc rzeczywistego zapłodnienia. Do komórki jajowej przesuwającej się jajowodem do macicy, dociera plemnik. Razem zamienią się w komórkę z 23 parami chromosomów – to zygota. Komórka dzieli się co kilkanaście godzin, aby ostatecznie rozwinął się z niej człowiek.',
        '',
        'Implantacja',
        'Implantation',
        '',
        ''),
       (4,
        'Na początku ciąży zygota przesuwa się w kierunku macicy i zagnieżdża się w niej. Odżywia się substancjami znajdującymi się w endometrium. Cały czas dzieli się, tworząc zarodek oraz część, z której powstanie łożysko, a wokół nich powstaje pęcherzyk ciążowy. Rozpoczyna się organogenza, czyli proces powstawania narządów i układów wewnętrznych.',
        '',
        'Twoje dziecko jest mniej więcej wielkości ziarenka maku',
        'Your baby is about the size of a poppy seed',
        '',
        ''),
       (5,
        'Pęcherzyk ciążowy, oprócz zarodka, mieści w sobie jeszcze pęcherzyk żółtkowy, wydzielający progesteron i jamę owodni. Rozwija się wątroba, nerki, a przede wszystkim mózg oraz rdzeń kręgowy oraz serce. Pojawiają się mięśnie i tkanki, formuje łożysko.',
        '',
        'Twoje dziecko jest mniej więcej wielkości nasionka sezamu',
        'Your baby is about the size of a sesame seed',
        '',
        ''),
       (6,
        'Zamyka się cewa nerwowa – jej niedomknięcie wiązałoby się z ryzykiem wad rozwojowych, jak rozszczep kręgosłupa lub wodogłowie. Serce płodu zaczyna bić i pompować krew do tworzącego się krwioobiegu. Tworzą się zalążki układu pokarmowego i oskrzela.',
        '',
        'Twoje dziecko jest mniej więcej wielkości soczewicy',
        'Your baby is about the size of a lentil',
        '',
        ''),
       (7,
        'W główce płodu powstają gałki oczne, uszy i nozdrza, języka i ust, a także zalążki zębów. Dziecko ma kształt kijanki, ale widoczne są już ręce i nóżki. Serce dzieli się na 2 komory, kształtuje się kościec zbudowany z miękkich chrząstek. Widać zawiązki narządów rodnych.',
        '',
        'Twoje dziecko jest mniej więcej wielkości jagody',
        'Your baby is about the size of a blueberry',
        '',
        ''),
       (8,
        'Embrion ma wyraźnie wyodrębnioną głowę z zarysowaną twarzyczką i tułów. Oczy dziecka mają już siatkówkę, rogówkę, tęczówkę i soczewkę. Powstaje ucho środkowe odpowiedzialne za równowagę. Tworzy się pępowina, doskonalą się narządy: wątroba, nerki, płuca.',
        '',
        'Twoje dziecko jest mniej więcej wielkości fasoli',
        'Your baby is about the size of a kidney bean',
        '1.57',
        '0.02'),
       (9,
        'Na kończynach malca widać już paluszki połączone błoną i opuszki. W pępowinie formują się jelita, które przemieszczają się do jamy brzusznej. W mózgu tworzą się pierwsze połączenia nerwowe.',
        '',
        'Twoje dziecko jest mniej więcej wielkości winogrona',
        'Your baby is about the size of a grape',
        '2.29',
        '0.03'),
       (10,
        'Rośnie mózg, a wraz z nim główka płodu. Formują się stawy, dlatego zgina on już rączki i nóżki. Rozwijają się płuca, powstaje przepona.',
        '',
        'Twoje dziecko jest mniej więcej wielkości kumkwatu',
        'Your baby is about the size of a kumquat',
        '3.1',
        '0.03'),
       (11,
        'Serce dzieli się na kolejne części i dostarcza krew do naczyń krwionośnych i narządów. Pępowina zasila krwią rozwijające się łożysko. Płód zaczyna intensywnie rosnąć, ma już teraz ok. 60 mm. Zaczynają pracować nerki, wydalając mocz do płynu owodniowego.',
        '',
        'Twoje dziecko jest mniej więcej wielkości figi',
        'Your baby is about the size of a fig',
        '4.09',
        '0.05'),
       (12,
        'Kończy się okres organogenezy, na ciele malca pojawia się meszek pełniący rolę termoregulacyjną. Płód pobiera glukozę z płynu owodniowego, zaczyna produkować też własne hormony. Maluszek potrafi ssać kciuk.',
        '',
        'Twoje dziecko jest mniej więcej wielkości limonki',
        'Your baby is about the size of a lime',
        '5.41',
        '0.06'),
       (13,
        'Zaczyna działać łożysko, które dostarcza płodowi tlenu i składników odżywczych. Dziecko jest bardzo ruchliwe, porusza kończynami, paluszkami, marszczy czoło. Oczy i uszy przesuwają się na właściwe sobie miejsca na twarzy.',
        '',
        'Twoje dziecko jest mniej więcej wielkości strąka grochu',
        'Your baby is about the size of a peapod',
        '6.71',
        '0.07'),
       (14,
        'Na skórze dziecka powstają komórki czuciowe. Formują się narządy płciowe dziecka: u dziewczynek pojawia się pochwa, macica i jajniki, w a nich komórki jajowe. Płód wdycha i wydycha płyn owodniowy, trenując odruch oddychania.',
        '',
        'Twoje dziecko jest mniej więcej wielkości cytryny',
        'Your baby is about the size of a lemon',
        '14.71',
        '0.09'),
       (15,
        'U dziecka rozwija się słuch - twardnieją kostki w uchu środkowym. Na buzi maluszka widać brwi, a na głowie – włoski.',
        '',
        'Twoje dziecko jest mniej więcej wielkości jabłka',
        'Your baby is about the size of an apple',
        '16.69',
        '0.12'),
       (16,
        'Organizm malca zatrzymuje wapń, dzięki czemu twardnieje jego kościec. Coraz mocniejsze są mięśnie dziecka, dzięki czemu potrafi ono koordynować ruchy swojego ciała.',
        '',
        'Twoje dziecko jest mniej więcej wielkości awokado',
        'Your baby is about the size of an avocado',
        '18.59',
        '0.15'),
       (17,
        'Narządy płciowe są na tyle duże i widoczne, że podczas badania USG można określić już płeć dziecka. Skóra płodu staje się grubsza, choć nadal jest przezroczysta.',
        '',
        'Twoje dziecko jest mniej więcej wielkości rzepy',
        'Your baby is about the size of a turnip',
        '20.4',
        '0.18'),
       (18,
        'Malec trenuje odruchy ssania i szukania pokarmu. Na jego opuszkach palców tworzą się linie papilarne. Dziecko reaguje na dotyk, odczuwa ciałem i wychwytuje uszami fale dźwiękowe, jego oczy są wrażliwe na światło. Jelita wypełniają się smółką.',
        '',
        'Twoje dziecko jest mniej więcej wielkości papryki',
        'Your baby is about the size of a bell pepper',
        '22.2',
        '0.22'),
       (19,
        'Układ nerwowy rozwija się produkują melinę – to substancja przewodząca impulsy i wpływająca na przyszłą inteligencję dziecka. Dzięki niej włókna nerwowe odtąd będą lepiej przewodziły impulsy. Układ pokarmowy dziecka zaczyna wydzielać soki trawienne.',
        '',
        'Twoje dziecko jest mniej więcej wielkości tradycyjnego pomidora',
        'Your baby is about the size of an heirloom tomato',
        '24',
        '0.27'),
       (20,
        'W mózgu płodu kształtują się komórki zmysłowe (smaku, powonienia, słuchu itd.). Tworzą się też połączenia nerwowe odpowiedzialne za pamięć i myślenie. W buzi dziecka powstają zalążki zębów.',
        '',
        'Twoje dziecko jest mniej więcej wielkości banana',
        'Your baby is about the size of a banana',
        '25.7',
        '0.33'),
       (21,
        'Nerki przejmują od łożyska funkcję produkcji płynu owodniowego. Filtrują też go i wytwarzają mocz, który za pośrednictwem krwiobiegu mamy jest wydalany na zewnątrz przez jej układ.',
        '',
        'Twoje dziecko jest mniej więcej wielkości marchewki',
        'Your baby is about the size of a carrot',
        '27.41',
        '0.4'),
       (22,
        'Rozwijają się gruczołu potowe na skórze, rosną paznokcie. U chłopców jądra zaczynają produkować plemniki.',
        '',
        'Twoje dziecko jest mniej więcej wielkości dyni makaronowej',
        'Your baby is about the size of a spaghetti squash',
        '29.01',
        '0.48'),
       (23,
        'Ciało maluszka nabiera proporcji zbliżonych do proporcji noworodka. Doskonali się słuch dziecka, które potrafi rozpoznać twój głos oraz głos taty – jeśli często go słyszy.',
        '',
        'Twoje dziecko jest mniej więcej wielkości dużego mango',
        'Your baby is about the size of a large mango',
        '30.61',
        '0.57'),
       (24,
        'Organizm rozpoczyna produkcję białych krwinek, odpowiedzialnych za odporność dziecka. Rozwijają się płuca, przygotowując się do wdychania tlenu w przyszłości – tworzą się przewody i pęcherzyki, rusza produkcja surfaktantu – substancji niezbędnej do sprawnego przebiegu procesu oddychania.',
        '',
        'Twoje dziecko jest mniej więcej wielkości kłosa kukurydzy',
        'Your baby is about the size of an ear of corn',
        '32.21',
        '0.67'),
       (25,
        'Powstają zawiązki zębów stałych, a w ustach – rozwijają się nerwy czuciowe potrzebne w przyszłości do sprawnego szukania piersi przez malca. Pępowina staje się gruba, zapewniając sprawny przepływ coraz większej ilości substancji i tlenu.',
        '',
        'Twoje dziecko jest mniej więcej wielkości brukwi',
        'Your baby is about the size of a rutabaga',
        '33.71',
        '0.78'),
       (26,
        'Wzmacnia się kręgosłup płodu i mięśnie. Warstwa tłuszczu w skórze zwiększa się, dzięki czemu malec staje się pulchniejszy.',
        '',
        'Twoje dziecko jest mniej więcej wielkości szalotki',
        'Your baby is about the size of a scallion',
        '35.1',
        '0.91'),
       (27,
        'Dzięki ssaniu kciuka dziecko wzmacnia mięśnie twarzy i jamy ustnej. Na języku formują się kubki smakowe. Malec otwiera i zamyka powieki, reagując na natężenie światła przechodzącego przez powłoki brzuszne mamy.',
        '',
        'Twoje dziecko jest mniej więcej wielkości główki kalafiora',
        'Your baby is about the size of a head of cauliflower',
        '36.6',
        '1.06'),
       (28,
        'Narządy wewnętrzne są na tyle rozwinięte, że organizm może skupić się na wzroście. Dziecko w tym wieku waży już ok. 1 kg. Jądra chłopców zstępują do moszny.',
        '',
        'Twoje dziecko jest mniej więcej wielkości dużego bakłażana',
        'Your baby is about the size of a large eggplant',
        '37.59',
        '1.21'),
       (29,
        'Dziecko jest coraz większe i jest mu coraz ciaśniej w macicy, dlatego mocniej odczuwasz każdy jego ruch. Mózg rozwija się intensywnie wpływając na kształt o wzrost główki. Jest silnie pofałdowany i nieustannie tworzy nowe połączenia nerwowe.',
        '',
        'Twoje dziecko jest mniej więcej wielkości dyni piżmowej',
        'Your baby is about the size of a butternut squash',
        '39.29',
        '1.38'),
       (30,
        'Zanika meszek pokrywający ciało dziecka, ale włosy na główce i rzęsy stają się coraz gęstsze. Szpik kostny produkuje czerwone krwinki. Wiele dzieci w tym wieku zmienia pozycję główką w dół.',
        '',
        'Twoje dziecko jest mniej więcej wielkości dużej kapusty',
        'Your baby is about the size of a large cabbage',
        '40.51',
        '1.56'),
       (31,
        'Malec ma wygląd noworodka, na USG można odczytać rysy jego twarzy. Stale rośnie, wydłużają się jego nogi. Płód ma wyraźny rytm snu i czuwania. Ożywia się, gdy coś zjesz i gdy odpoczywasz, a w ciągu dnia śpi kołysany ruchami twojego ciała.',
        '',
        'Twoje dziecko jest mniej więcej wielkości kokosa',
        'Your baby is about the size of a coconut',
        '41.81',
        '1.75'),
       (32,
        'Malec uczy się obracania główką na boki, otwiera i zamyka oczy, stale ćwiczy płuca pobudzając produkcję surfaktantu.',
        '',
        'Twoje dziecko jest mniej więcej wielkości kłębiana',
        'Your baby is about the size of a jicama',
        '43',
        '1.95'),
       (33,
        'Rośnie główka dziecka, robiąc miejsce dla stale rosnącego mózgu – w ciągu tygodnia może powiększyć się ona nawet o 9 mm. Zwiększa się tez ilość tłuszczu w skórze malca.',
        '',
        'Twoje dziecko jest mniej więcej wielkości ananasa',
        'Your baby is about the size of a pineapple',
        '44.09',
        '2.16'),
       (34,
        'Rozwija się układ immunologiczny dziecka, dzięki czemu malec nabiera odporności. Rosną ostre paznokietki na dłoniach i stópkach.',
        '',
        'Twoje dziecko jest mniej więcej wielkości kantalupy',
        'Your baby is about the size of a cantaloupe',
        '45.31',
        '2.38'),
       (35,
        'Centralny układ nerwowy jest w pełni dojrzały, jeśli dziecko urodziłoby się teraz, podjął by działanie. Sprawnie funkcjonuje układ pokarmowy.',
        '',
        'Twoje dziecko jest mniej więcej wielkości melona spadziowego',
        'Your baby is about the size of a honeydew melon',
        '46.3',
        '2.59'),
       (36, 'Dziecko rośnie, dlatego ma coraz mniej miejsca. Rozpycha się, dając ci mocne kuksańce.',
        '',
        'Twoje dziecko jest mniej więcej wielkości główki sałaty rzymskiej',
        'Your baby is about the size of a head of romaine lettuce',
        '47.29',
        '2.81'),
       (37,
        'Jeśli malec do tej pory nie zmienił pozycji, to ma na to coraz mniejsze szanse – brak miejsca utrudnia fikołki, mimo to istnieje jeszcze taka możliwość. Działa układ odpornościowy dziecka. Masa dziecka w tym wieku to ok. 3 kg.',
        '',
        'Twoje dziecko jest mniej więcej wielkości pęczka boćwiny',
        'Your baby is about the size of a bunch of Swiss chard',
        '48.31',
        '3.03'),
       (38,
        'Ciąża jest już donoszona, co oznacza, że dziecko może bezpiecznie się urodzić i że może stać się to w każdej chwili. Łożysko starzeje się, czyli przestaje pełnić swoje funkcje – to naturalny objaw zbliżającego się porodu. Jelita wypełnia smółka, pierwsze odchody, które będą wydalone po porodzie. Dziecko wpasowuje się główką w kanał rodny, dlatego możesz zauważyć opuszczenie się brzucha.',
        '',
        'Twoje dziecko jest mniej więcej wielkości pora',
        'Your baby is about the size of a leek',
        '49.3',
        '3.23'),
       (39,
        'Płuca są gotowe do podjęcia oddychania, Dzięki obecności w nich surfaktantu, zapobiegającemu sklejanie się pęcherzyków płucnych. Pępowina jest długa, często owija malca, ale nie martw się – w czasie porodu może się to zmienić.',
        '',
        'Twoje dziecko jest mniej więcej wielkości miniarbuza',
        'Your baby is about the size of a mini-watermelon',
        '50.09',
        '3.43'),
       (40,
        'Dziecko ma w pełni rozwinięty szkielet i narządy, gotowe do podjęcia samodzielnej pracy poza macicą. Jest gotowe do narodzin.',
        '',
        'Twoje dziecko jest mniej więcej wielkości małej dyni',
        'Your baby is about the size of a small pumpkin',
        '51',
        '3.62');


DROP TABLE IF EXISTS article;

CREATE TABLE article
(
    id             SERIAL PRIMARY KEY,
    category       VARCHAR,
    title_pl       VARCHAR,
    title_en       VARCHAR,
    description_pl VARCHAR,
    description_en VARCHAR,
    image_name     VARCHAR,
    content_pl     VARCHAR,
    content_en     VARCHAR,
    published      BOOLEAN DEFAULT TRUE,
    published_date VARCHAR
);

INSERT INTO article (category, title_pl, title_en, description_pl, description_en, image_name, content_pl, content_en,
                     published_date)
VALUES ('health', 'Tytuł 1', 'Title 1', 'Opis 1', 'Description 1', 'article1.jpg', '<h3>zawartość1</h3>',
        '<h3>content1</h3>',
        '12/12/2023'),
       ('health', 'Tytuł 2', 'Title 2', 'Opis 2', 'Description 2', 'article2.jpg', '<h3>zawartość2</h3>',
        '<h3>content2</h3>',
        '19/06/2023'),
       ('layette', 'Tytuł 1', 'Title 1', 'Opis 1', 'Description 1', 'article1.jpg', '<h3>zawartość1</h3>',
        '<h3>content1</h3>',
        '12/12/2023'),
       ('layette', 'Tytuł 1', 'Title 1', 'Opis 1', 'Description 1', 'article1.jpg', '<h3>zawartość1</h3>',
        '<h3>content1</h3>',
        '12/12/2023'),
       ('layette', 'Tytuł 1', 'Title 1', 'Opis 1', 'Description 1', 'article1.jpg', '<h3>zawartość1</h3>',
        '<h3>content1</h3>',
        '12/12/2023');